### Seamless Bay Area Tweet Analysis: Part 4, Modeling


The goal of this project is to analyze the twitter account of the nonprofit group Seamless Bay Area and determine what makes up the most high-impact tweet as measured by engagements.

In part four we start doing modeling, either to see if there is a direct linear relationship between any tweet features and engagements or if any emergent categories of tweets are predictive.

In [1]:
# Load necessary libraries
import pandas as pd
import numpy as np
import statistics as stat
import re
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv("/Users/grahamsmith/Documents/SpringboardWork/Seamless_Twitter_Analysis/tweets with features.csv")

In [8]:
sentiment = pd.read_csv('/Users/grahamsmith/Documents/SpringboardWork/Seamless_Twitter_Analysis/sentiment scores.csv')

In [3]:
#Here is out data for ref
df.head()

,Unnamed: 0.1,Unnamed: 0,Tweet text,time,impressions,engagements,engagement rate,retweets,replies,likes,user profile clicks,url clicks,tweet words,links,replies_sentance
0,0,0,@MTCBATA is looking for a new Executive Direct...,2018-10-27 18:01:00,124.0,5.0,0.040323,0.0,[['@MTCBATA']],0.0,1.0,4.0,"['@mtcbata', 'is', 'looking', 'for', 'a', 'new...",https://t.co/Syf9exwPTd,"['@MTCBATA', 'is', 'looking', 'for', 'a', 'new..."
1,1,1,Ultimate seamlessness. https://t.co/CdCLrg2o6a,2018-10-26 14:24:00,345.0,10.0,0.028986,0.0,[],1.0,0.0,9.0,"['ultimate', 'seamlessness.', 'https://t.co/cd...",https://t.co/CdCLrg2o6a,"['Ultimate', 'seamlessness.', 'https://t.co/Cd..."
2,2,2,Help Nix Prop 6! Save funding for more seamles...,2018-10-26 02:28:00,994.0,19.0,0.019115,4.0,[],5.0,3.0,5.0,"['help', 'nix', 'prop', 'save', 'funding', 'fo...","https://t.co/qM4M7tCFVO, https://t.co/2379qGdY2D","['Help', 'Nix', 'Prop', '6!', 'Save', 'funding..."
3,3,3,It doesn't have to be this way! Let's get to f...,2018-10-23 23:29:00,792.0,7.0,0.008838,2.0,[],4.0,1.0,0.0,"['it', ""doesn't"", 'have', 'to', 'be', 'this', ...",https://t.co/FczQtLbH5d,"['It', ""doesn't"", 'have', 'to', 'be', 'this', ..."
4,4,4,And then come say hi at next month’s @SPUR_Urb...,2018-10-23 23:09:00,532.0,3.0,0.005639,0.0,"[['@SPUR_Urbanist'], ['@icgee']]",1.0,2.0,0.0,"['and', 'then', 'come', 'say', 'hi', 'at', 'ne...",NaN,"['And', 'then', 'come', 'say', 'hi', 'at', 'ne..."

In [9]:
sentiment.head()

,Unnamed: 0,engagements,rep_,"rep_""@AsmMarcBermans""","rep_""@Caltrains""","rep_""@DavidChius""","rep_""@GavinNewsoms""","rep_""@MTCBATAs""","rep_""@MetroTransitMNs""","rep_""@MosesMaynez""",...,rep3_@sfmta_muni,rep3_@skbarz,rep3_@stevepepple,rep3_@theGreaterMarin,rep3_@thecliffbar,rep3_@transpoakland,rep3_@urbenschneider,rep3_@wpusanews.,rep3_@xentrans!,rep3_@yimbyyy
0,0,5.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,10.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,19.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,7.0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,3.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0